config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#home'
  get '/lien-he', to: 'application#contact'
  post '/lien-he', to: 'application#contact'
  get '/ve-cong-ty', to: 'application#about'
  get '/tuyen-dung', to: 'application#recruitment'
  get '/du-an', to:'application#highlight'
  get '/catalog/:slug', to:'application#catalog'
  get '/project/:slug', to:'application#project'

  get '/tin-tuc', to:'application#darkhouse_news'
  get '/tin-tuc/:slug', to:'application#darkhouse_news_detail'

  namespace :admin do
    root to: "dashboard#index"
    post '/upload-image/:news_id', to:'photos#upload_image'
    post '/sort-image', to:'photos#sort_image'
    resources :categories, :news, :users, :abouts, :recruitments, :photos, :customer_comments, :darkhouse_news, :appointments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/darkhouse_news.rb
class DarkhouseNews < ApplicationRecord
    has_paper_trail
    paginates_per 10
    validates :title,:image, presence: {message: "phải điền"}
    mount_uploader :image, MediaUploader
    has_many :photos, :dependent => :destroy
    belongs_to :created_by_user, :class_name => 'User', foreign_key: :create_by_id
    belongs_to :updated_by_user, :class_name => 'User', foreign_key: :updated_by_id, optional: true
    accepts_nested_attributes_for :photos

    before_save :to_slug
    private def to_slug
        self.slug = title.parameterize.truncate(80, omission: "")
    end
    
    before_destroy :delete_remote_file, prepend: true
    private def delete_remote_file
        if self.image?
            self.image.file.delete
        end
    end
end

app/controllers/admin/darkhouse_news_controller.rb
class Admin::DarkhouseNewsController < AdminController
    
    def index
        @darkhouse_news = DarkhouseNews.page params[:page]
    end

    def new
        @darkhouse_news = DarkhouseNews.new
        @photos = @darkhouse_news.photos.build
    end

    def create
        begin
            @darkhouse_news = current_user.darkhouse_news_created.create!(darkhouse_news_params)
            if(@darkhouse_news && params[:photos])
                params[:photos]['image'].each do |a|
                    @photo = @darkhouse_news.photos.create!(:image => a)
                end
            end
            flash[:success] = 'Tạo tin tức thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def show
        @darkhouse_news = DarkhouseNews.find(params[:id])
    end
    
    def update
        begin
            @darkhouse_news = DarkhouseNews.find(params[:id])
            @darkhouse_news.update(darkhouse_news_params)
            @darkhouse_news.update(updated_by_id: current_user.id)
            if(@darkhouse_news && params[:photos])
                params[:photos]['image'].each do |a|
                    @photo = @darkhouse_news.photos.create!(:image => a)
                end
            end
            flash[:success] = 'Lưu tin tức thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def destroy
        begin
            @darkhouse_news = DarkhouseNews.find(params[:id]).destroy
            flash[:success] = 'Xoá tin tức thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def darkhouse_news_params
        params.require(:darkhouse_news).permit(
            :title,
            :sort_content,
            :content,
            :active,
            :highlight,
            :image,
            :image_cache,
            photos_attributes: [:id, :image, :darkhouse_news_id])
    end

end

app/views/admin/darkhouse_news/index.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
        <li class="breadcrumb-item active">Danh sách tin tức</li>
      </ol>
    </nav>
    <a href="/admin/darkhouse_news/new"><i class="material-icons text-primary">add_circle</i></a>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Tiêu đề</th>
            <th>Đăng bởi</th>
            <th>Cập nhật bởi</th>
            <th>Trạng thái</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @darkhouse_news.each do |news| %>
          <tr>
            <!--<td><%= cl_image_tag(news.image.thumbnail) %></td>-->
            <td><%= news.title %></td>
            <td><%= news.created_by_user.email %></td>
            <td><%= news.updated_by_user ? news.updated_by_user.email : '' %></td>
            <td><%= news.active ? 'Active':'Inactive' %></td>
            <td class="text-center" style="width: 1%">
              <div class="d-flex">
                <a href="/admin/darkhouse_news/<%= news.id %>"><i class="material-icons">edit</i></a>
                <a class="ml-2" target="_blank" rel="noopener noreferrer" href="/project/<%= news.slug %>"><i class="fas fa-eye"></i></a>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @darkhouse_news %>
    </div>
</div>

app/views/admin/darkhouse_news/new.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin/darkhouse_news">Danh sách tin tức</a></li>
            <li class="breadcrumb-item active">Tạo tin tức</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-12">
        <h2>Tin tức mới</h2>
        <%= form_for([:admin,@darkhouse_news]) do |f| %>
            <div class="form-group">
                <label>Tiêu đề</label>
                <%= f.text_field :title, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group form-inline">
                <label>Trạng thái</label>
                <div class="custom-control custom-switch ml-5">
                    <%= f.check_box :active, class: "custom-control-input", id: 'activeSwitch'  %>
                    <label class="custom-control-label" for="activeSwitch"></label>
                </div>
            </div>
            <div class="form-group form-inline">
                <label>Hiển thị trên trang chủ</label>
                <div class="custom-control custom-switch ml-5">
                    <%= f.check_box :highlight, class: "custom-control-input", id: 'highlightSwitch'  %>
                    <label class="custom-control-label" for="highlightSwitch"></label>
                </div>
            </div>
            <div class="form-group">
                <label>Ảnh bìa</label>
                <button class="btn mt-1 pl-0" type="button" id="select-image-button"><i class="material-icons">camera_alt</i></button>   
                <%= f.hidden_field :image_cache %>
                <%= f.file_field :image, class: "form-control d-none", id: 'file-input' %>
                <div id="image-preview"></div>
            </div>
            
            <div class="form-group">
                <label>Tóm tắt</label>
                <%= f.text_area :sort_content, class: "form-control" %>
            </div>
            <div class="form-group">
                <label>Nội dung</label>
                <%= f.text_area :content, class: "form-control", id: 'editor'  %>
            </div>
            <div class="form-group">
                <label>Thư viện ảnh</label>
                <button class="btn mt-1 pl-0" type="button" id="select-photo-button"><i class="material-icons">camera_alt</i></button>   
                <%= f.file_field :photos, multiple: true, class: "form-control d-none", id: 'photo-input', name: "photos[image][]" %>
                <div id="photo-preview"></div>
            </div>
            
            <div class="text-right mt-2">
                <button class="btn btn-primary" type="submit">Tạo Tin tức</button>
            </div>
        <% end %>
        </div>
    </div>
</div>
<script>
    $('#select-image-button').on('click',()=>{
        $('#file-input').click()
    })
    $('#file-input').on('change',(e)=>{
        $('#image-preview').empty()
        let reader = new FileReader();
        reader.readAsDataURL(e.target.files[0]);
        reader.onload = function () {
            $('#image-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    })
    $('#select-photo-button').on('click',()=>{
        $('#photo-input').click()
    })
    $('#photo-input').on('change',(e)=>{
        $('#photo-preview').empty()
        let files = e.target.files
        for(let i =0; i<files.length;i++){
            let reader = new FileReader();
            reader.readAsDataURL(files[i]);
            reader.onload = function () {
                $('#photo-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
            };
            reader.onerror = function (error) {
                console.log('Error: ', error);
            };
        }
        
    })
    CKEDITOR.replace('editor');
</script>
    

app/views/admin/darkhouse_news/show.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin/news">Danh sách bài đăng</a></li>
            <li class="breadcrumb-item active">Sửa bài đăng</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-12">
        <h2>Sửa bài đăng</h2>
        <%= form_for([:admin,@darkhouse_news],:html => { :onsubmit => "updateSort(event)" }) do |f| %>
            <div class="form-group">
                <label>Tiêu đề</label>
                <%= f.text_field :title, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group form-inline">
                <label>Trạng thái</label>
                <div class="custom-control custom-switch ml-5">
                    <%= f.check_box :active, class: "custom-control-input", id: 'activeSwitch'  %>
                    <label class="custom-control-label" for="activeSwitch"></label>
                </div>
            </div>
            <div class="form-group form-inline">
                <label>Hiển thị trên trang chủ</label>
                <div class="custom-control custom-switch ml-5">
                    <%= f.check_box :highlight, class: "custom-control-input", id: 'highlightSwitch'  %>
                    <label class="custom-control-label" for="highlightSwitch"></label>
                </div>
            </div>
            <div class="form-group">
                <label>Ảnh bìa</label>
                <button class="btn mt-1 pl-0" type="button" id="select-image-button"><i class="material-icons">camera_alt</i></button>
                <div id="image-preview">
                    <img src="<%=@darkhouse_news.image.thumbnail %>">
                </div>
                <%= f.hidden_field :image_cache %>
                <%= f.file_field :image, class: "form-control d-none", id: 'file-input' %>
            </div>
            <div class="form-group">
                <label>Tóm tắt</label>
                <%= f.text_area :sort_content, class: "form-control" %>
            </div>
            <div class="form-group">
                <label>Nội dung</label>
                <%= f.text_area :content, class: "form-control", id: 'editor'  %>
            </div>
            <div class="form-group">
                <label>Thư viện ảnh</label>
                <button class="btn mt-1 pl-0" type="button" id="select-photo-button"><i class="material-icons">camera_alt</i></button>   
                <%= f.file_field :photos, multiple: true, class: "form-control d-none", id: 'photo-input', name: "photos[image][]" %>
            </div>
            <div class="d-block d-md-flex flex-wrap" id="sortable-images">
                <% @darkhouse_news.photos.where(image_type: nil).order(:sort).each_with_index do |photo,index| %>
                    <div class="ml-1 mt-1 border border-success position-relative text-center" data-id="<%= photo.id %>">
                        <div class="position-absolute bg-success text-white rounded-circle p-1" style="top:5px;left:5px;">
                            <div class="text-center" style="width:20px;height:20px;">
                                <%= photo.sort %>
                            </div>
                        </div>
                        <img style="height:100px;width:auto" src="<%=photo.image.thumbnail %>"/>
                        <a class="position-absolute text-danger" style="top:5px;right:5px" href="/admin/photos/<%= photo.id %>" data-method="delete" data-confirm="Are you sure?">
                            <i class="material-icons">clear</i>
                        </a>
                    </div>
                <% end %>
            </div>
            <div id="photo-preview"></div>
            <div class="text-right mt-2">
                <button class="btn btn-primary" type="submit">Lưu Bài Đăng</button>
                <%= link_to 'Xoá tin tức', admin_darkhouse_news_path(@darkhouse_news), class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Delete this news ?' } %>
            </div>
        <% end %>
        </div>
        <div class="col-12 mt-3">
            <h2>Log</h2>
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <% @darkhouse_news.versions.map do |version| %>
                        <tr>
                            <td><%= version.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                            <td><%= version.event %></td>
                            <td><%= User.find(version.whodunnit).email %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $('#select-image-button').on('click',()=>{
        $('#file-input').click()
    })
    $('#file-input').on('change',(e)=>{
        $('#image-preview').empty()
        let reader = new FileReader();
        reader.readAsDataURL(e.target.files[0]);
        reader.onload = function () {
            $('#image-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    })
    $('#select-photo-button').on('click',()=>{
        $('#photo-input').click()
    })
    $('#photo-input').on('change',(e)=>{
        $('#photo-preview').empty()
        let files = e.target.files
        for(let i =0; i<files.length;i++){
            let reader = new FileReader();
            reader.readAsDataURL(files[i]);
            reader.onload = function () {
                $('#photo-preview').append('<img class="ml-1 mt-1 border border-danger" style="height:100px;width:auto" src="'+reader.result+'"/>')
            };
            reader.onerror = function (error) {
                console.log('Error: ', error);
            };
        }
        
    })
    CKEDITOR.replace( 'editor',{ 
        filebrowserUploadUrl: '/admin/upload-image/<%=@darkhouse_news.id%>',
        extraPlugins: 'uploadimage',
        uploadUrl: '/admin/upload-image/<%=@darkhouse_news.id%>'
    });
    var sort_data = new Sortable(document.getElementById('sortable-images'), {
        swapThreshold: 1,
        animation: 150
    });
    function updateSort(e){
        jQuery.ajax('/admin/sort-image',{ method:"POST", data:{ ids:sort_data.toArray() }}).then((res)=>{
            console.log(res)
        })
    }
</script>
        