config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#home'
  get '/lien-he', to: 'application#contact'
  post '/lien-he', to: 'application#contact'
  get '/ve-cong-ty', to: 'application#about'
  get '/tuyen-dung', to: 'application#recruitment'
  get '/du-an', to:'application#highlight'
  get '/catalog/:slug', to:'application#catalog'
  get '/project/:slug', to:'application#project'

  get '/tin-tuc', to:'application#darkhouse_news'
  get '/tin-tuc/:slug', to:'application#darkhouse_news_detail'

  namespace :admin do
    root to: "dashboard#index"
    post '/upload-image/:news_id', to:'photos#upload_image'
    post '/sort-image', to:'photos#sort_image'
    resources :categories, :news, :users, :abouts, :recruitments, :photos, :customer_comments, :darkhouse_news, :appointments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_paper_trail
    paginates_per 10
    validates :name,:image, presence: {message: "phải điền"}
    mount_uploader :image, MediaUploader
    has_many :news, :dependent => :destroy

    before_save :to_slug
    private def to_slug
        self.slug = name.parameterize.truncate(80, omission: "")
    end

    before_destroy :delete_remote_file, prepend: true
    private def delete_remote_file
        if self.image?
            self.image.file.delete
        end
    end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    def index
        @categories = Category.page params[:page]
    end

    def new
        @category = Category.new
    end

    def create
        begin
            Category.create!(category_params)
            flash[:success] = 'Tạo Catalog thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def show
        @category = Category.find(params[:id])
    end
    
    def update
        begin
            @category = Category.find(params[:id])
            @category.update_attributes(category_params)
            flash[:success] = 'Lưu catalog thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def destroy
        begin
            puts params[:id]
            Category.find(params[:id]).destroy
            flash[:success] = 'Xoá catalog thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def category_params
        params.require(:category).permit(:name,:active,:description,:image,:image_cache)
    end
end

app/views/admin/categories/index.html.erb
<div class="container-fluid">
  <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
        <li class="breadcrumb-item active">Danh sách catalog</li>
      </ol>
  </nav>
  <a href="/admin/categories/new"><i class="material-icons text-primary">add_circle</i></a>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Tên</th>
          <th>Trạng thái</th>
          <th># bài</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= category.active ? 'Active':'Inactive' %></td>
            <td class="text-center" style="width: 5%"><%= category.news.count %></td>
            <td class="text-center" style="width: 1%"><a href="/admin/categories/<%= category.id %>"><i class="material-icons">edit</i></a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @categories %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin/categories">Danh sách catalog</a></li>
            <li class="breadcrumb-item active">Tạo catalog</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-12">
        <h2>Catalog mới</h2>
        <%= form_for([:admin,@category]) do |f| %>
            <div class="form-group">
                <label>Tên catalog</label>
                <%= f.text_field :name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
                <label>Mô tả</label>
                <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group form-inline">
                <label>Trạng thái</label>
                <div class="custom-control custom-switch ml-5">
                    <%= f.check_box :active, class: "custom-control-input", id: 'activeSwitch'  %>
                    <label class="custom-control-label" for="activeSwitch"></label>
                </div>
            </div>
            <div class="form-group">
                <label>Ảnh bìa</label>
                <button class="btn mt-1 pl-0" type="button" id="select-image-button"><i class="material-icons">camera_alt</i></button>   
                <%= f.hidden_field :image_cache %>
                <%= f.file_field :image, class: "form-control d-none", id: 'file-input' %>
                <div id="image-preview"></div>
            </div>
            <div class="text-right">
                <button class="btn btn-primary" type="submit">Tạo Catalog</button>
            </div>
        <% end %>
        </div>
    </div>
</div>
<script>
     $('#select-image-button').on('click',()=>{
        $('#file-input').click()
    })
    $('#file-input').on('change',(e)=>{
        $('#image-preview').empty()
        let reader = new FileReader();
        reader.readAsDataURL(e.target.files[0]);
        reader.onload = function () {
            $('#image-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    })
</script>
                

app/views/admin/categories/show.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin/categories">Danh sách catalog</a></li>
            <li class="breadcrumb-item active">Sửa catalog</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-12">
        <h2>Sửa catalog</h2>
        <%= form_for([:admin,@category]) do |f| %>
            <div class="form-group">
                <label>Tên catalog</label>
                <%= f.text_field :name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
                <label>Mô tả</label>
                <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group form-inline">
                <label>Active status</label>
                <div class="custom-control custom-switch ml-5">
                    <%= f.check_box :active, class: "custom-control-input", id: 'activeSwitch'  %>
                    <label class="custom-control-label" for="activeSwitch"></label>
                </div>
            </div>
            <div class="form-group">
                <label>Ảnh bìa</label>
                <button class="btn mt-1 pl-0" type="button" id="select-image-button"><i class="material-icons">camera_alt</i></button>
                <div id="image-preview">
                    <img src="<%=@category.image.thumbnail %>">
                </div>
                <%= f.hidden_field :image_cache %>
                <%= f.file_field :image, class: "form-control d-none", id: 'file-input' %>
            </div>
            <div class="text-right">
                <button class="btn btn-primary" type="submit">Lưu Catalog</button>
                <%= link_to 'Xoá catalog', admin_category_path(@category), class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Delete this category ?' } %>
            </div>
        <% end %>
        </div>
        <div class="col-12 mt-3">
            <h2>Log</h2>
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <% @category.versions.map do |version| %>
                        <tr>
                            <td><%= version.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                            <td><%= version.event %></td>
                            <td><%= User.find(version.whodunnit).email %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $('#select-image-button').on('click',()=>{
        $('#file-input').click()
    })
    $('#file-input').on('change',(e)=>{
        $('#image-preview').empty()
        let reader = new FileReader();
        reader.readAsDataURL(e.target.files[0]);
        reader.onload = function () {
            $('#image-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    })
</script>
            