config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#home'
  get '/lien-he', to: 'application#contact'
  post '/lien-he', to: 'application#contact'
  get '/ve-cong-ty', to: 'application#about'
  get '/tuyen-dung', to: 'application#recruitment'
  get '/du-an', to:'application#highlight'
  get '/catalog/:slug', to:'application#catalog'
  get '/project/:slug', to:'application#project'

  get '/tin-tuc', to:'application#darkhouse_news'
  get '/tin-tuc/:slug', to:'application#darkhouse_news_detail'

  namespace :admin do
    root to: "dashboard#index"
    post '/upload-image/:news_id', to:'photos#upload_image'
    post '/sort-image', to:'photos#sort_image'
    resources :categories, :news, :users, :abouts, :recruitments, :photos, :customer_comments, :darkhouse_news, :appointments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer_comment.rb
class CustomerComment < ApplicationRecord
    has_paper_trail
    paginates_per 10
    validates :name,:image, presence: {message: "phải điền"}
    mount_uploader :image, MediaUploader

    before_destroy :delete_remote_file, prepend: true
    private def delete_remote_file
        if self.image?
            self.image.file.delete
        end
    end
end

app/controllers/admin/customer_comments_controller.rb
class Admin::CustomerCommentsController < AdminController
    def index
        @customer_comments = CustomerComment.page params[:page]
    end

    def new
        @customer_comment = CustomerComment.new
    end

    def create
        begin
            CustomerComment.create!(customer_comment_params)
            flash[:success] = 'Tạo Comment thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def show
        @customer_comment = CustomerComment.find(params[:id])
    end
    
    def update
        begin
            @customer_comment = CustomerComment.find(params[:id])
            @customer_comment.update(customer_comment_params)
            flash[:success] = 'Lưu catalog thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def destroy
        begin
            puts params[:id]
            CustomerComment.find(params[:id]).destroy
            flash[:success] = 'Xoá catalog thành công'
            redirect_to action: :index
        rescue => ex
            flash[:error] = ex.message
            redirect_back fallback_location: root_path
        end
    end

    def customer_comment_params
        params.require(:customer_comment).permit(:name,:quote,:image,:image_cache)
    end
end

app/views/admin/customer_comments/index.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
          <li class="breadcrumb-item active">Danh sách bình luận</li>
        </ol>
    </nav>
    <a href="/admin/customer_comments/new"><i class="material-icons text-primary">add_circle</i></a>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Tên</th>
            <th>Bình luận</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @customer_comments.each do |customer_comment| %>
            <tr>
              <td><%= customer_comment.name %></td>
              <td><%= customer_comment.quote %></td>
              <td class="text-center" style="width: 1%"><a href="/admin/customer_comments/<%= customer_comment.id %>"><i class="material-icons">edit</i></a></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customer_comments %>
    </div>
</div>
  

app/views/admin/customer_comments/new.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin/customer_comments">Danh sách bình luận</a></li>
            <li class="breadcrumb-item active">Tạo bình luận</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-12">
        <h2>Bình luận mới</h2>
        <%= form_for([:admin,@customer_comment]) do |f| %>
            <div class="form-group">
                <label>Tên khách hàng</label>
                <%= f.text_field :name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
                <label>Bình luận</label>
                <%= f.text_area :quote, class: "form-control" %>
            </div>
            <div class="form-group">
                <label>Ảnh đại diện</label>
                <button class="btn mt-1 pl-0" type="button" id="select-image-button"><i class="material-icons">camera_alt</i></button>   
                <%= f.hidden_field :image_cache %>
                <%= f.file_field :image, class: "form-control d-none", id: 'file-input' %>
                <div id="image-preview"></div>
            </div>
            <div class="text-right">
                <button class="btn btn-primary" type="submit">Tạo Bình luận</button>
            </div>
        <% end %>
        </div>
    </div>
</div>
<script>
     $('#select-image-button').on('click',()=>{
        $('#file-input').click()
    })
    $('#file-input').on('change',(e)=>{
        $('#image-preview').empty()
        let reader = new FileReader();
        reader.readAsDataURL(e.target.files[0]);
        reader.onload = function () {
            $('#image-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    })
</script>
                

app/views/admin/customer_comments/show.html.erb
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin/categories">Danh sách bình luận</a></li>
            <li class="breadcrumb-item active">Sửa bình luận</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-12">
        <h2>Sửa bình luận</h2>
        <%= form_for([:admin,@customer_comment]) do |f| %>
            <div class="form-group">
                <label>Tên khách hàng</label>
                <%= f.text_field :name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
                <label>Bình luận</label>
                <%= f.text_area :quote, class: "form-control" %>
            </div>
            <div class="form-group">
                <label>Ảnh đại diện</label>
                <button class="btn mt-1 pl-0" type="button" id="select-image-button"><i class="material-icons">camera_alt</i></button>
                <div id="image-preview">
                    <img src="<%=@customer_comment.image.thumbnail %>">
                </div>
                <%= f.hidden_field :image_cache %>
                <%= f.file_field :image, class: "form-control d-none", id: 'file-input' %>
            </div>
            <div class="text-right">
                <button class="btn btn-primary" type="submit">Lưu Comment</button>
                <%= link_to 'Xoá bình luận', admin_customer_comment_path(@customer_comment), class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Delete this comment ?' } %>
            </div>
        <% end %>
        </div>
        <div class="col-12 mt-3">
            <h2>Log</h2>
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <tbody>
                        <% @customer_comment.versions.map do |version| %>
                        <tr>
                            <td><%= version.created_at.strftime("%d/%m/%Y %H:%M") %></td>
                            <td><%= version.event %></td>
                            <td><%= User.find(version.whodunnit).email %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $('#select-image-button').on('click',()=>{
        $('#file-input').click()
    })
    $('#file-input').on('change',(e)=>{
        $('#image-preview').empty()
        let reader = new FileReader();
        reader.readAsDataURL(e.target.files[0]);
        reader.onload = function () {
            $('#image-preview').append('<img class="ml-1 mt-1" style="height:100px;width:auto" src="'+reader.result+'"/>')
        };
        reader.onerror = function (error) {
            console.log('Error: ', error);
        };
    })
</script>
            